"""Build hooks: keep private, generated and linked content out of every archive, at any depth.

MANIFEST.in globs cannot express "this directory name at any depth", so the same predicate is
applied in three places: the manifest list (which becomes the sdist member list and SOURCES.txt),
the wheel's package-data collection, and the sdist copy step. All metadata stays in
pyproject.toml. Reviewed public exceptions are listed in documentation/ARCHIVE_POLICY.json.
"""
import json
import os
import posixpath
import re

from setuptools import setup
from setuptools.command import egg_info
from setuptools.command.build_py import build_py as _build_py
from setuptools.command.sdist import sdist as _sdist

ROOT = os.path.dirname(os.path.abspath(__file__))
POLICY = os.path.join(ROOT, 'documentation', 'ARCHIVE_POLICY.json')
PRIVATE_DIRECTORIES = frozenset(('.crewloom', '.git', 'node_modules', '.next', 'build', 'dist', '.venv', 'venv',
                                 '.tox', '.nox', '.pytest_cache', '.mypy_cache', '__pycache__'))
PRIVATE_FILE = re.compile(r'(^\.env($|\.)|\.env$|^runs\.jsonl$|^events\.jsonl$|\.py[co]$|^\.DS_Store$|\.log$)')
TEMPLATES = frozenset(('.env.example', '.env.template'))  # secret-free templates stay source


def approved_paths():
    try:
        with open(POLICY, encoding='utf-8') as handle:
            value = json.load(handle).get('approved_public_paths', [])
    except (OSError, ValueError):
        return frozenset()
    return frozenset(item for item in value if isinstance(item, str))


def is_private(relative):
    """True when a repository-relative path is private/generated by name, at any depth."""
    path = posixpath.normpath(relative.replace('\\', '/'))
    while path.startswith('./'):
        path = path[2:]
    if path in ('', '.') or path in approved_paths():
        return False
    parts = path.split('/')
    if any(part in PRIVATE_DIRECTORIES or part.endswith('.egg-info') for part in parts[:-1]):
        return True
    name = parts[-1]
    if name in PRIVATE_DIRECTORIES or name.endswith('.egg-info'):
        return True
    return name not in TEMPLATES and bool(PRIVATE_FILE.search(name))


def is_excluded(relative, root=ROOT):
    """Private by name, or any symlink (a link can carry content from outside the checkout)."""
    if is_private(relative):
        return True
    current = root
    for part in posixpath.normpath(relative.replace('\\', '/')).split('/'):
        current = os.path.join(current, part)
        if os.path.islink(current):
            return True
    return False


_original_prune = egg_info.manifest_maker.prune_file_list


def _prune_file_list(self):
    _original_prune(self)
    self.filelist.files[:] = [name for name in self.filelist.files if not is_excluded(name)]


egg_info.manifest_maker.prune_file_list = _prune_file_list


class build_py(_build_py):
    def exclude_data_files(self, package, src_dir, files):
        kept = super().exclude_data_files(package, src_dir, files)
        return [name for name in kept
                if not is_excluded(os.path.relpath(os.path.abspath(name), ROOT).replace(os.sep, '/'))]


class sdist(_sdist):
    def make_release_tree(self, base_dir, files):
        super().make_release_tree(base_dir, [name for name in files if not is_excluded(name)])


setup(cmdclass={'build_py': build_py, 'sdist': sdist})
