#!/usr/bin/env python3
"""Credential-verified reviewer identities for manual acceptance decisions.

A reviewer credential proves that its caller holds the secret issued to a registered
principal. It is deliberately narrow about what that proves: possession of a registered
principal's secret, and nothing about the real world. It does not establish that a
different human was present, that the human read the artifacts, or that the artifacts
are correct.

This credential never substitutes for recorded verification. Acceptance commands still
need executor evidence, and lesson promotion still needs
`project_lessons.executor_evidence`. Only the manual `workflow accept` decision for a
`task` step is gated here, and only when a project opts in through `policy.review` in
`crewloom.project.json`.

Registered tokens are 256-bit values generated by this module, so they are hashed with
SHA-256 rather than a slow password KDF: there is no low-entropy secret to brute force,
and a fast hash keeps constant-time comparison cheap. Only the hash, the principal, the
method, and non-secret metadata are ever stored.

Authenticity of a stored decision comes from the registry acting as the issuance
authority, not from a checksum the record itself could recompute. Each credential has an
`epoch`, and the per-credential proof key is derived from the epoch together with the
stored token hash, which only the owner-only registry holds. A proof is therefore
verifiable only against the credential that actually issued it: editing the principal,
the decision time, the scope, or the artifacts invalidates the signature, and a revoked
or reissued credential derives a different key so earlier approvals stop verifying.
"""
import argparse
import hashlib
import hmac
import json
import os
import re
import secrets
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import workflow as w

REGISTRY_NAME = '.crewloom/reviewers.json'
SCHEMA_VERSION = 1
TOKEN_BYTES = 32
TOKEN_ENV = 'CREWLOOM_REVIEWER_TOKEN'
LABEL_METHOD = 'declared-label'
CREDENTIAL_METHOD = 'hashed-token'
MODES = ('label', 'verified')
LIMIT = 64
IDENTIFIER = re.compile(r'[a-z0-9]+(?:-[a-z0-9]+)*$')
PROOF_FIELDS = ('schema_version', 'principal', 'method', 'project_id', 'checkout_id', 'workflow_id',
                'step_id', 'role', 'artifact_sha256', 'criteria_sha256', 'decided_at', 'nonce',
                'credential_epoch')
KEY_DERIVATION = b'crewloom-review-proof-key-v1'
SIGNATURE_DOMAIN = b'crewloom-review-proof-signature-v1'
ENTRY_FIELDS = {'principal', 'token_sha256', 'method', 'label', 'revoked', 'registered_at', 'revoked_at', 'epoch'}


class ReviewError(ValueError):
    """A review decision is refused; nothing is written when this is raised."""


def now():
    return datetime.now(timezone.utc).isoformat(timespec='seconds')


def registry_path(root):
    """The issuance authority, inside the protected runtime directory.

    It deliberately is not a trackable project file. Its token hashes and per-credential
    epochs are the material every stored approval is signed with, so a registry at the
    project root could be declared as a workflow input, copied into a task context body,
    committed, or indexed by a symbol map. Under `.crewloom` it is resolved with the
    internal runtime path rule instead: never a symlink, never outside the project, and
    never reachable as a declared artifact.
    """
    return w.safe_path(root, REGISTRY_NAME, internal=True)


def _ownership_problems(path):
    """Refuse a registry other users or groups can read, or that another user owns.

    POSIX permission bits are the only portable signal available, so the check applies
    there. Windows and other platforms without POSIX modes have no equivalent to inspect
    here; those platforms get no such guarantee, which `status` states rather than implies.
    """
    if os.name != 'posix':
        return []
    info = path.stat()
    problems = []
    if info.st_uid != os.getuid():
        problems.append('Reviewer registry must be owned by the current user')
    if info.st_mode & 0o077:
        problems.append('Reviewer registry must not be readable by group or other (chmod 600)')
    return problems


def _entry_problems(entry):
    if not isinstance(entry, dict):
        return ['entries must be objects']
    unknown = set(entry) - ENTRY_FIELDS
    problems = ['unknown fields: ' + ', '.join(sorted(unknown))] if unknown else []
    principal = entry.get('principal')
    if not isinstance(principal, str) or not principal.strip() or len(principal) > 100 or '\n' in principal:
        problems.append('principal must be short nonempty text')
    elif not IDENTIFIER.fullmatch(principal.strip()) and '@' not in principal:
        problems.append('principal must be a kebab-case id or an email-like identity')
    digest = entry.get('token_sha256')
    if not isinstance(digest, str) or len(digest) != 64 or any(item not in '0123456789abcdef' for item in digest):
        problems.append('token_sha256 must be a lowercase SHA-256 hex digest')
    epoch = entry.get('epoch')
    if not isinstance(epoch, str) or len(epoch) != 32 or any(item not in '0123456789abcdef' for item in epoch):
        problems.append('epoch must be a 128-bit lowercase hex issuance generation')
    if entry.get('method') != CREDENTIAL_METHOD:
        problems.append('method must be ' + CREDENTIAL_METHOD)
    if not isinstance(entry.get('revoked'), bool):
        problems.append('revoked must be true or false')
    if not isinstance(entry.get('registered_at'), str):
        problems.append('registered_at must be recorded')
    return problems


def validate(value):
    """Strict schema: an unknown or malformed field blocks the project instead of guessing."""
    if not isinstance(value, dict):
        raise ReviewError('Malformed reviewer registry')
    unknown = set(value) - {'schema_version', 'project_id', 'reviewers'}
    if unknown:
        raise ReviewError('Unknown reviewer registry fields: ' + ', '.join(sorted(unknown)))
    if value.get('schema_version') != SCHEMA_VERSION:
        raise ReviewError('Reviewer registry requires schema_version ' + str(SCHEMA_VERSION))
    if not isinstance(value.get('project_id'), str) or not value['project_id']:
        raise ReviewError('Reviewer registry needs the owning project id')
    reviewers = value.get('reviewers')
    if not isinstance(reviewers, list) or len(reviewers) > LIMIT:
        raise ReviewError('Reviewer registry needs at most ' + str(LIMIT) + ' entries')
    problems = []
    seen = set()
    for entry in reviewers:
        problems.extend(_entry_problems(entry))
        principal = entry.get('principal') if isinstance(entry, dict) else None
        if isinstance(principal, str):
            if principal in seen:
                problems.append('duplicate principal: ' + principal)
            seen.add(principal)
    if problems:
        raise ReviewError('Malformed reviewer registry: ' + '; '.join(problems))
    return value


def load(root, required=False):
    path = registry_path(root)
    if not path.exists():
        if required:
            raise ReviewError('No reviewer registry in this project. Register one with '
                              '`crewloom reviewer register --project <root> --principal <id>`.')
        return None
    if path.is_symlink() or not path.is_file() or path.stat().st_nlink != 1:
        raise ReviewError('Reviewer registry must be a regular file without hardlinks')
    problems = _ownership_problems(path)
    if problems:
        raise ReviewError('; '.join(problems))
    try:
        return validate(json.loads(path.read_text(encoding='utf-8')))
    except (OSError, ValueError) as exc:
        if isinstance(exc, ReviewError):
            raise
        raise ReviewError('Malformed reviewer registry: ' + str(exc))


def _write(root, value):
    """Atomically write the registry and keep it owner-only, because it gates acceptance."""
    path = registry_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + '\n'
    with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=path.parent, delete=False) as stream:
        temporary = Path(stream.name)
        stream.write(data)
    try:
        os.chmod(temporary, 0o600)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()
    return path


def _write_secret(root, principal, token):
    """Publish a freshly issued credential to an owner-only file, never to a log.

    Printing it would put it in terminal scrollback, CI output, and any process that
    captures this command, exactly where a reviewer credential must not be. Only the path
    is reported; the operator reads the file when they need it.
    """
    path = w.safe_path(root, '.crewloom/reviewer-token-' + principal, internal=True)
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=path.parent, delete=False) as stream:
        temporary = Path(stream.name)
        stream.write(token + '\n')
    try:
        os.chmod(temporary, 0o600)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()
    os.chmod(path, 0o600)
    return path


def register(root, principal, label=None):
    """Add or replace one principal and return its token exactly once; only the hash is stored.

    Reissuing a principal mints a fresh token and a fresh `epoch`, which is what makes any
    approval the previous credential signed stop verifying afterwards.
    """
    if not isinstance(principal, str) or not principal.strip() or len(principal) > 100:
        raise ReviewError('A reviewer needs a short nonempty principal')
    principal = principal.strip()
    problems = _entry_problems({'principal': principal, 'token_sha256': '0' * 64,
                                'method': CREDENTIAL_METHOD, 'revoked': False,
                                'registered_at': now(), 'epoch': '0' * 32})
    if problems:
        raise ReviewError('; '.join(problems))
    project_id, _ = w.binding_id(root)
    if not project_id:
        raise ReviewError('Bind the project before registering reviewers: `crewloom project bootstrap`')
    existing = load(root) or {'schema_version': SCHEMA_VERSION, 'project_id': project_id, 'reviewers': []}
    if existing['project_id'] != project_id:
        raise ReviewError('Reviewer registry belongs to another project')
    token = secrets.token_urlsafe(TOKEN_BYTES)
    entry = {'principal': principal, 'token_sha256': hashlib.sha256(token.encode()).hexdigest(),
             'method': CREDENTIAL_METHOD, 'revoked': False, 'registered_at': now(),
             'epoch': secrets.token_hex(16)}
    if label:
        entry['label'] = str(label)[:200]
    kept = [item for item in existing['reviewers'] if item['principal'] != principal]
    kept.append(entry)
    if len(kept) > LIMIT:
        raise ReviewError('Reviewer registry holds at most ' + str(LIMIT) + ' entries')
    _write(root, {**existing, 'reviewers': kept})
    return principal, token


def revoke(root, principal):
    """Revoke a principal and rotate its issuance generation.

    Rotating the epoch on revocation means a decision signed under the old generation
    cannot be replayed even against a restored copy of the registry.
    """
    registry = load(root, required=True)
    entry = next((item for item in registry['reviewers'] if item['principal'] == principal), None)
    if entry is None:
        raise ReviewError('Unknown reviewer principal: ' + str(principal))
    entry['revoked'] = True
    entry['revoked_at'] = now()
    entry['epoch'] = secrets.token_hex(16)
    _write(root, registry)
    return principal


def resolve_principal(registry, token):
    """Constant-time lookup across every entry, so a miss never reveals which entry was near."""
    if not isinstance(token, str) or not token:
        raise ReviewError('A reviewer credential is required')
    presented = hashlib.sha256(token.encode()).hexdigest()
    match = None
    for entry in registry['reviewers']:
        if hmac.compare_digest(entry['token_sha256'], presented) and not entry['revoked']:
            match = entry
    if match is None:
        raise ReviewError('Reviewer credential is unknown, revoked, or malformed')
    return match


def proof_key(entry):
    """Per-credential proof key, derived from the issuance generation and stored token hash.

    The registry is the issuance authority: it is owner-only, and the key exists nowhere
    else, so a proof cannot be re-signed without the credential's current generation.
    """
    material = '|'.join((entry['token_sha256'], entry['epoch'], str(entry['principal'])))
    return hmac.new(KEY_DERIVATION, material.encode('utf-8'), hashlib.sha256).digest()


def sign(entry, proof):
    """HMAC over the decision content, so any edited field invalidates the signature."""
    payload = '|'.join((SIGNATURE_DOMAIN.decode('ascii'), str(proof.get('principal')),
                        str(proof.get('credential_epoch')), str(proof_digest(proof))))
    return hmac.new(proof_key(entry), payload.encode('utf-8'), hashlib.sha256).hexdigest()


def signature_matches(entry, proof):
    """Constant-time signature check against the registry entry that supposedly issued it."""
    signature = proof.get('signature')
    if not isinstance(signature, str) or len(signature) != 64:
        return False
    return hmac.compare_digest(signature, sign(entry, proof))


def policy(root):
    """Effective review policy; an absent block keeps the compatible declared-label mode."""
    import project_binding as pb
    config, _ = pb.load_config(root)
    block = ((config or {}).get('policy') or {}).get('review') or {}
    return {'mode': block.get('mode', 'label'), 'allow_self_review': bool(block.get('allow_self_review', False))}


def criteria_digest(root, criteria):
    """Hash the acceptance criteria this decision was made against, when the plan names any."""
    if not criteria:
        return None
    path = w.safe_path(root, criteria)
    return w.digest(path.read_bytes()) if path.is_file() else None


def binding(root, workflow_id, step, outputs, criteria=None):
    """The scoped identity one acceptance decision is authorized for."""
    project_id, checkout_id = w.binding_id(root)
    return {'schema_version': SCHEMA_VERSION, 'project_id': project_id or '', 'checkout_id': checkout_id or '',
            'workflow_id': workflow_id, 'step_id': step['id'], 'role': step['role'],
            'artifact_sha256': w.digest(json.dumps(outputs, sort_keys=True).encode()),
            'criteria_sha256': criteria_digest(root, criteria)}


def proof_digest(proof):
    """Integrity digest over a stored proof, so any edited field is detectable."""
    if not isinstance(proof, dict):
        return None
    return w.digest(json.dumps({field: proof.get(field) for field in PROOF_FIELDS}, sort_keys=True).encode())


def seal(scope, principal, method, entry=None):
    """Build one proof record: identity, method, and audit material only, never a credential."""
    proof = {**{field: scope[field] for field in PROOF_FIELDS if field in scope},
             'principal': principal, 'method': method, 'decided_at': now(),
             'nonce': secrets.token_hex(16), 'credential_epoch': entry['epoch'] if entry else None}
    if entry is not None:
        proof['signature'] = sign(entry, proof)
    return proof


def authorize(root, workflow_id, step, outputs, criteria=None, label=None, token=None):
    """Authorize one manual acceptance, or refuse. This function writes nothing."""
    settings = policy(root)
    if settings['mode'] not in MODES:
        raise ReviewError('Review policy mode must be one of: ' + ', '.join(MODES))
    if settings['mode'] == 'label':
        if not isinstance(label, str) or not label.strip() or len(label) > 100:
            raise ReviewError('Task completion needs a reviewer identifier')
        principal, method, entry = label.strip(), LABEL_METHOD, None
    else:
        entry = resolve_principal(load(root, required=True), token)
        principal, method = entry['principal'], CREDENTIAL_METHOD
    if not settings['allow_self_review'] and principal == step['role']:
        raise ReviewError('Task completion needs a reviewer different from the owning role')
    proof = seal(binding(root, workflow_id, step, outputs, criteria), principal, method, entry)
    return {**proof, 'proof_sha256': proof_digest(proof)}


def verify(proof, scope, method):
    """Structural, integrity, and scope checks that need no registry access."""
    if not isinstance(proof, dict) or set(proof) != set(PROOF_FIELDS) | {'proof_sha256', 'signature'}:
        return 'invalid'
    if proof.get('proof_sha256') != proof_digest(proof):
        return 'tampered'
    if proof.get('method') != method:
        return 'unverified'
    if any(proof.get(field) != value for field, value in scope.items()):
        return 'stale'
    return 'valid'


def verify_credential(root, proof):
    """Verify a credential-signed proof against the project registry as issuance authority.

    Fails closed for every reason a stored approval should stop authorizing a decision:
    no registry, another project's registry, an unregistered or revoked principal, a
    superseded issuance generation, or a signature the current generation cannot produce.
    """
    try:
        registry = load(root)
    except ReviewError:
        return 'unregistered'
    if registry is None:
        return 'unregistered'
    project_id, _ = w.binding_id(root)
    if registry['project_id'] != proof.get('project_id') or registry['project_id'] != (project_id or ''):
        return 'cross-project'
    entry = next((item for item in registry['reviewers']
                  if item['principal'] == proof.get('principal')), None)
    if entry is None:
        return 'unregistered'
    if entry['revoked']:
        return 'revoked'
    if not hmac.compare_digest(entry['epoch'], str(proof.get('credential_epoch') or '')):
        return 'superseded'
    if not signature_matches(entry, proof):
        return 'unsigned'
    return 'valid'


def verify_record(root, record, step, workflow_id, outputs, criteria=None, method=LABEL_METHOD):
    """Check a recorded review proof against the identity, artifacts, and criteria it claimed."""
    proof = record.get('review') if isinstance(record, dict) else None
    if not isinstance(proof, dict):
        return 'missing'
    scope = binding(root, workflow_id, step, outputs, criteria)
    outcome = verify(proof, scope, method)
    if outcome != 'valid':
        return outcome
    if method == CREDENTIAL_METHOD:
        return verify_credential(root, proof)
    return outcome


def credential_from_environment(stream=None):
    """Read a credential from the environment or standard input, never from a command line."""
    token = os.environ.get(TOKEN_ENV, '').strip()
    if token:
        return token
    if stream is None:
        return None
    return (stream.read() or '').strip() or None


def status(root):
    """Operational summary that never includes credential material."""
    path = registry_path(root)
    refusal = None
    try:
        registry = load(root)
    except ReviewError as exc:
        registry, refusal = None, str(exc)
    return {'project_root': str(root), 'registry': str(path), 'registry_present': registry is not None,
            'registry_mode': oct(path.stat().st_mode & 0o777) if path.exists() else None,
            'registry_refused': refusal,
            'review_policy': policy(root),
            'reviewers': [{'principal': item['principal'], 'method': item['method'], 'revoked': item['revoked'],
                           'label': item.get('label'), 'registered_at': item['registered_at']}
                          for item in (registry or {}).get('reviewers', [])],
            'limitation': 'A credential proves possession of a registered principal’s secret. It does '
                          'not prove that a distinct human reviewed the work.',
            'authenticity': 'Each approval is HMAC-signed with a key derived from the owner-only '
                            'reviewer registry in .crewloom, so editing a stored decision, or replaying '
                            'one after revocation or reissue, fails closed.',
            'platform_limits': 'On POSIX the registry must be a single-link regular file owned by the '
                               'current user with no group or other permission, and a refusal stops '
                               'verified review from authorizing anything. Platforms without POSIX '
                               'modes cannot be checked this way; use filesystem access control there '
                               'and do not treat a successful load as proof of exclusive access.',
            'residual_risk': 'Every process running as the project owner can still read the registry, '
                             'so this is an integrity boundary against record tampering and casual '
                             'disclosure, not an OS sandbox against the project owner.',
            'enforcement_boundary': 'Only `workflow accept` for a task step is gated. Acceptance commands, '
                                    'lesson promotion, and lesson verification keep their own executor evidence.'}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest='action', required=True)
    for name, helptext in (('status', 'Show the review policy and registered principals'),
                           ('register', 'Issue a credential; the token is written to an owner-only file'),
                           ('revoke', 'Revoke a registered principal')):
        sub = commands.add_parser(name, help=helptext)
        sub.add_argument('--project', default='.', help='Bound project root (default: current directory)')
        if name in ('register', 'revoke'):
                sub.add_argument('--principal', required=True)
                if name == 'register':
                    sub.add_argument('--label')
                    sub.add_argument('--show-token', action='store_true',
                                     help='Also print the issued token on stdout; off by default so it '
                                          'cannot reach a log')
    args = parser.parse_args(argv)
    try:
        root = Path(args.project).resolve(strict=True)
        if not root.is_dir():
            raise ReviewError('Project must be a directory')
        if args.action == 'status':
            print(json.dumps(status(root), ensure_ascii=False, indent=2))
            return 0
        if args.action == 'register':
            principal, token = register(root, args.principal, args.label)
            secret = _write_secret(root, principal, token)
            report = {'project_root': str(root), 'principal': principal, 'method': CREDENTIAL_METHOD,
                      'token_file': str(secret),
                      'instruction': 'Read it from that file into CREWLOOM_REVIEWER_TOKEN or standard '
                                     'input. Only the hash is stored, so a lost token cannot be '
                                     'recovered; reissue the principal to mint a new one.'}
            if args.show_token:
                report['token'] = token
            print(json.dumps(report, ensure_ascii=False, indent=2))
            return 0
        revoke(root, args.principal)
        print(json.dumps({'project_root': str(root), 'principal': args.principal, 'revoked': True}))
        return 0
    except (ValueError, OSError) as exc:
        print(json.dumps({'status': 'blocked', 'error': str(exc)}, ensure_ascii=False))
        return 2


if __name__ == '__main__':
    raise SystemExit(main())