"""Coordinator regressions: preflight refusals, ownership, resume, integration and publication.

The real-Docker class at the end is opt-in and is the only place that proves a batch ran the
isolated executor and a combined acceptance for actual; everything above it runs offline against
Git alone.
"""
import hashlib
import fcntl
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

SOURCE = Path(__file__).resolve().parent
sys.path.insert(0, str(SOURCE))

import crewloom
import model_host
import project_binding as pb
import repo_map
import task_coordinator as tc
import workflow as w

ROLE = 'context-guardian'


ACCEPTANCE = '''import hashlib
import json
import sys
from pathlib import Path

EXPECTED = {'left.txt': 'marked left', 'right.txt': 'marked right', 'combine.txt': 'marked combine'}
results = {}
for name in sorted(EXPECTED):
    path = Path(name)
    text = path.read_text(encoding='utf-8') if path.is_file() else ''
    results[name] = {'present': bool(text), 'marker_found': EXPECTED[name] in text,
                     'sha256': hashlib.sha256(text.encode()).hexdigest() if text else None}
combined = all(item['present'] and item['marker_found'] for item in results.values())
Path('artifacts').mkdir(exist_ok=True)
Path('artifacts/acceptance.json').write_text(json.dumps(
    {'combined_acceptance': combined, 'artifacts': results}, indent=2), encoding='utf-8')
sys.exit(0 if combined else 1)
'''


def _builder(body):
    return ('from pathlib import Path\nimport sys\n'
            'target = Path(sys.argv[1])\n'
            'marker = sys.argv[2] if len(sys.argv) > 2 else ""\n'
            'target.parent.mkdir(parents=True, exist_ok=True)\n'
            + body)


# The model-task fixture below generates these modules through a stand-in provider, then the
# acceptance commands import and run them inside a real container. The generated code is the
# actual artifact under test: the checks are numeric behaviour, never a marker string.
GENERATED = {
    'double': '"""Generated left pricing feature."""\n\nLABEL = \'left\'\n\n\n'
              'def double(value):\n    """Double one integer value."""\n'
              '    return value * 2\n',
    'triple': '"""Generated right tax feature."""\n\nLABEL = \'right\'\n\n\n'
              'def triple(value):\n    """Triple one integer value."""\n'
              '    return value * 3\n',
}

ACCEPT_FEATURE = '''import hashlib
import importlib.util
import json
import sys
from pathlib import Path

module_path, expected_label, output = sys.argv[1], sys.argv[2], sys.argv[3]
spec = importlib.util.spec_from_file_location('generated_feature', module_path)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
observed = {'label': module.LABEL, 'value': module.double(21) if expected_label == 'left'
            else module.triple(14),
            'source_sha256': hashlib.sha256(Path(module_path).read_bytes()).hexdigest()}
if observed['label'] != expected_label or observed['value'] != 42:
    raise SystemExit('the generated feature did not behave as required: ' + json.dumps(observed))
Path(output).write_text(json.dumps(observed, indent=2), encoding='utf-8')
'''

ACCEPT_COMBINED = '''import hashlib
import importlib.util
import json
import sys
from pathlib import Path

results = {}
sources = {}
for label, path in (('left', 'src/left_feature.py'), ('right', 'src/right_feature.py')):
    spec = importlib.util.spec_from_file_location('combined_' + label, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    sources[label] = hashlib.sha256(Path(path).read_bytes()).hexdigest()
    results[label] = json.loads(Path('artifacts/' + label + '_result.json').read_text(encoding='utf-8'))
    if module.LABEL != label or results[label]['label'] != label:
        raise SystemExit('combined acceptance saw the wrong module for ' + label)
    value = module.double(21) if label == 'left' else module.triple(14)
    if value != 42 or results[label]['value'] != 42:
        raise SystemExit('combined acceptance saw broken generated behaviour for ' + label)
    if results[label]['source_sha256'] != sources[label]:
        raise SystemExit('the task acceptance did not read the committed generated bytes for ' + label)
Path('artifacts/acceptance.json').write_text(json.dumps(
    {'combined_acceptance': True, 'modules': sources, 'observed': results}, indent=2),
    encoding='utf-8')
'''


def _stand_in_provider(requests):
    """A provider stand-in that answers only from the real request payload.

    It reads the prompt the managed executor actually sent, returns the declared output paths
    through the adapter's own `validate_artifacts`, and records the host it was asked for. No
    network, CLI or credential is involved: the point is the orchestration around generation, not
    a model. Every claim about what was generated stays checkable from the recorded requests.
    """
    def generate(host, prompt, outputs, timeout=180, model=None, max_output_tokens=None):
        # W09: inside a batch the adapter is now told its output ceiling; the stand-in records it.
        payload = json.loads(prompt.split('\n', 1)[1])
        requests.append({'host': host, 'model': model, 'ceiling': max_output_tokens, 'task': payload['task'],
                         'inputs': [item['path'] for item in payload['inputs']],
                         'outputs': list(payload['outputs'])})
        function = 'double' if 'left' in payload['task'] else 'triple'
        content = GENERATED[function]
        artifacts = {'artifacts': [{'path': path, 'content': content} for path in outputs]}
        return model_host.validate_artifacts(artifacts, outputs), {
            'host': host, 'model_reported': None, 'model_requested': model,
            'usage': {'input_tokens': len(prompt), 'output_tokens': len(content)},
            'execution_boundary': 'fixture stand-in provider; no network, CLI or credential'}
    return generate


class CoordinatorFixture(unittest.TestCase):
    """A disposable bound Git project with three task workflows and one integration workflow.

    The frozen repository is built once per class and copied per test, because the interesting
    cost here is Git process latency: every refusal case needs a real repository, and building one
    from scratch in each of two dozen cases buys nothing that a copy does not.
    """

    template = None

    @classmethod
    def setUpClass(cls):
        temporary = tempfile.TemporaryDirectory(prefix='crewloom-coordinator-template-')
        cls.addClassCleanup(temporary.cleanup)
        cls.template = Path(temporary.name).resolve() / 'project'
        cls.template.mkdir()
        cls._build(cls.template)

    @staticmethod
    def _git(root, *arguments):
        result = subprocess.run(['git', *arguments], cwd=str(root), env=repo_map.git_environment(),
                                capture_output=True, text=True, check=True, timeout=30)
        return result.stdout.strip()

    @classmethod
    def _build(cls, root):
        cls._git(root, 'init', '-q')
        cls._git(root, 'config', 'gc.auto', '0')
        cls._git(root, 'config', 'maintenance.auto', 'false')
        cls._git(root, 'config', 'user.name', 'Coordinator fixture')
        cls._git(root, 'config', 'user.email', 'fixture@example.invalid')
        # The catalog role a plan names is resolved from the installed library, not from this
        # project, so the fixture stays a bare bound repository instead of copying a role tree.
        config = pb.default_config('coordinator-fixture', 'observe')
        (root / pb.CONFIG_NAME).write_text(json.dumps(config))
        pb.bootstrap(root, project_id='coordinator-fixture')
        (root / 'input.txt').write_text('frozen fixture input\n')
        (root / 'criteria.md').write_text('- Every declared output exists and passes its check.\n')
        (root / 'builder.py').write_text(_builder(
            'target.write_text("artifact for %s marked %s at the frozen base\\n"\n'
            '                   % (target.name, marker))\n'))
        (root / 'left.txt').write_text('base content\n')
        (root / 'verify_combined.py').write_text(ACCEPTANCE)
        (root / 'workflows').mkdir()
        for name in ('left', 'right', 'combine', 'integration'):
            plan = {'schema_version': 1, 'id': name + '-workflow', 'criteria': 'criteria.md',
                    'steps': [{'id': 'build', 'role': ROLE,
                               'summary': 'Build one independently scoped artifact',
                               'argv': ['python3', 'builder.py', name + '.txt', name],
                               'inputs': ['input.txt', 'builder.py'],
                               'outputs': [name + '.txt']}]}
            if name == 'integration':
                plan['steps'][0] = {'id': 'accept', 'role': 'qa-test-automation-engineer',
                                    'summary': 'Accept the combined result of every task',
                                    'argv': ['python3', 'verify_combined.py'],
                                    'inputs': ['input.txt', 'verify_combined.py', 'left.txt',
                                               'right.txt', 'combine.txt'],
                                    'outputs': ['artifacts/acceptance.json']}
            (root / 'workflows' / (name + '.json')).write_text(json.dumps(plan))
        (root / 'coordinator.json').write_text(json.dumps(cls.plan_definition()))
        cls._git(root, 'add', '.')
        cls._git(root, 'commit', '-qm', 'Freeze the coordinator fixture')

    @staticmethod
    def plan_definition():
        return {'schema_version': 1, 'id': 'feature-batch',
                'project_id': 'coordinator-fixture', 'base': 'HEAD', 'workers': 2,
                'tasks': [{'id': 'left', 'workflow': 'workflows/left.json', 'depends_on': []},
                          {'id': 'right', 'workflow': 'workflows/right.json', 'depends_on': []},
                          {'id': 'combine', 'workflow': 'workflows/combine.json',
                           'depends_on': ['left', 'right']}],
                'integration': {'workflow': 'workflows/integration.json'}}

    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix='crewloom-coordinator-')
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).resolve() / 'project'
        shutil.copytree(self.template, self.root, symlinks=True)
        binding = pb.load_binding(self.root, allow_moved=True)
        binding['project_root'] = str(self.root)
        (self.root / pb.BINDING_RELATIVE).write_text(json.dumps(binding))
        self.plan = json.loads((self.root / 'coordinator.json').read_text())
        self.base = self.git('rev-parse', 'HEAD')

    def git(self, *arguments):
        return self._git(self.root, *arguments)

    def write_plan(self):
        (self.root / 'coordinator.json').write_text(json.dumps(self.plan))

    def snapshot(self):
        return {str(path.relative_to(self.root)): (
            hashlib.sha256(path.read_bytes()).hexdigest(), path.stat().st_mode, path.stat().st_mtime_ns)
            for path in self.root.rglob('*') if path.is_file() and not path.is_symlink()
            # Git's own background maintenance may add object-store files while a test runs; refs,
            # the index, HEAD and every working file stay compared, so a coordinator write still shows.
            and path.relative_to(self.root).parts[:2] != ('.git', 'objects')}

    def cli(self, action, project_id='coordinator-fixture', *extra):
        return subprocess.run([sys.executable, str(SOURCE / 'crewloom.py'), 'coordinator', action,
                               '--project', str(self.root), '--project-id', project_id,
                               '--manifest', 'coordinator.json', *extra], cwd=str(self.root),
                              env=repo_map.git_environment(), capture_output=True, text=True,
                              timeout=180)

    def call(self, action, **kwargs):
        return tc.__dict__[action](self.root, 'coordinator.json', 'coordinator-fixture', **kwargs)

    def worktree(self, ident):
        return self.root / '.crewloom/worktrees/feature-batch' / ident


class PreflightBoundaries(CoordinatorFixture):
    def test_a_valid_dag_validates_without_writing_anything(self):
        before = self.snapshot()
        result = self.cli('validate')
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        report = json.loads(result.stdout)
        self.assertEqual(report['status'], 'validated')
        self.assertEqual(report['order'], ['left', 'right', 'combine'])
        self.assertEqual(report['base_commit'], self.base)
        self.assertEqual(self.snapshot(), before, 'Read-only preflight wrote project state')

    def test_a_missing_local_binding_is_refused_without_guessing_identity(self):
        (self.root / '.crewloom/binding.json').unlink()
        result = self.cli('validate')
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('not bound', result.stdout)

    def test_a_foreign_project_identity_is_refused(self):
        result = self.cli('validate', 'another-project')
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('project identity', result.stdout.lower())

    def test_a_dirty_tracked_base_is_refused_and_preserved(self):
        (self.root / 'input.txt').write_text('local uncommitted edit\n')
        before = (self.root / 'input.txt').read_text()
        result = self.cli('validate')
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual((self.root / 'input.txt').read_text(), before)

    def test_staged_changes_are_refused_and_preserved(self):
        (self.root / 'input.txt').write_text('staged user change\n')
        self.git('add', 'input.txt')
        before = self.snapshot()
        self.assertNotEqual(self.cli('validate').returncode, 0)
        self.assertEqual(self.snapshot(), before)

    def test_unknown_option_like_and_missing_base_refs_are_refused(self):
        for base in ('--help', 'no-such-ref', 'HEAD^{tree}', 'a b', '..'):
            self.plan['base'] = base
            self.write_plan()
            self.git('add', 'coordinator.json')
            self.git('commit', '--allow-empty', '-qm', 'Freeze base ' + base)
            before = self.snapshot()
            self.assertNotEqual(self.cli('validate').returncode, 0, base)
            self.assertEqual(self.snapshot(), before, base)
        self.plan['base'] = 'HEAD'
        self.write_plan()

    def test_a_ref_that_does_not_name_the_checked_out_head_is_refused(self):
        self.git('checkout', '-q', '-b', 'other-base')
        self.git('checkout', '-q', '-')
        self.plan['base'] = 'other-base'
        self.write_plan()
        self.git('add', 'coordinator.json')
        self.git('commit', '-qm', 'Freeze a mismatched base')
        self.assertNotEqual(self.cli('validate').returncode, 0)

    def test_cycles_duplicates_and_unknown_keys_are_refused_without_writes(self):
        cases = [
            lambda: self.plan['tasks'][0].__setitem__('depends_on', ['combine']),
            lambda: self.plan['tasks'][1].__setitem__('id', 'left'),
            lambda: self.plan['tasks'][0].__setitem__('depends_on', ['left']),
            lambda: self.plan['tasks'][0].__setitem__('depends_on', ['missing']),
            lambda: self.plan['tasks'][0].__setitem__('surprise', True),
            lambda: self.plan.__setitem__('workers', 5),
            lambda: self.plan.__setitem__('workers', 0),
            lambda: self.plan.__setitem__('workers', True),
            lambda: self.plan.__setitem__('unexpected', 1),
            lambda: self.plan.__setitem__('language', 'fr'),
        ]
        for mutate in cases:
            with self.subTest(mutate=mutate):
                original = json.loads(json.dumps(self.plan))
                mutate()
                self.write_plan()
                self.git('add', 'coordinator.json')
                self.git('commit', '--allow-empty', '-qm', 'Freeze an invalid manifest')
                before = self.snapshot()
                result = self.cli('validate')
                self.assertNotEqual(result.returncode, 0)
                self.assertIn('error', result.stdout.lower())
                self.assertEqual(self.snapshot(), before)
                self.plan = original
                self.write_plan()
                self.git('add', 'coordinator.json')
                self.git('commit', '--allow-empty', '-qm', 'Restore the valid manifest')

    def test_a_non_git_root_is_refused_and_an_outside_manifest_is_refused(self):
        plain = Path(tempfile.mkdtemp(prefix='crewloom-plain-'))
        self.addCleanup(shutil.rmtree, str(plain), True)
        (plain / 'coordinator.json').write_text('{}')
        with self.assertRaisesRegex(ValueError, 'git project|Git'):
            tc.validate(plain, 'coordinator.json', 'coordinator-fixture')
        outside = Path(tempfile.mkdtemp(prefix='crewloom-outside-'))
        self.addCleanup(shutil.rmtree, str(outside), True)
        (outside / 'other.json').write_text(json.dumps(self.plan))
        with self.assertRaisesRegex(ValueError, 'escapes'):
            tc.validate(self.root, '../' + str(outside)[1:].replace('/', '/'), 'coordinator-fixture')

    def test_a_task_workflow_without_an_integration_input_is_refused(self):
        plan = json.loads((self.root / 'workflows/integration.json').read_text())
        plan['steps'][0]['inputs'] = ['input.txt', 'builder.py']
        (self.root / 'workflows/integration.json').write_text(json.dumps(plan))
        self.git('add', 'workflows/integration.json')
        self.git('commit', '-qm', 'Narrow the integration inputs')
        before = self.snapshot()
        result = self.cli('validate')
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('integration workflow must declare', result.stdout)
        self.assertEqual(self.snapshot(), before)

    def test_a_manual_task_step_is_refused_before_anything_runs(self):
        plan = json.loads((self.root / 'workflows/left.json').read_text())
        plan['steps'][0]['kind'] = 'task'
        (self.root / 'workflows/left.json').write_text(json.dumps(plan))
        self.git('add', 'workflows/left.json')
        self.git('commit', '--allow-empty', '-qm', 'Declare a manual task step')
        result = self.cli('validate')
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('execute no manual task step', result.stdout)

    def test_a_symlinked_worktree_path_is_refused(self):
        outside = Path(tempfile.mkdtemp(prefix='crewloom-redirect-'))
        self.addCleanup(shutil.rmtree, str(outside), True)
        batch = self.root / '.crewloom/worktrees/feature-batch'
        batch.mkdir(parents=True)
        (batch / 'left').symlink_to(outside)
        with self.assertRaisesRegex(ValueError, 'escapes'):
            self.call('start')
        self.assertEqual(list(outside.iterdir()), [], 'the redirect target stayed untouched')
        self.assertFalse((self.root / '.crewloom/coordinators/feature-batch/state.json').exists()
                         and json.loads((self.root / '.crewloom/coordinators/feature-batch/state.json')
                                        .read_text())['tasks']['left']['worktree'])


class OwnershipBoundaries(CoordinatorFixture):
    def test_a_live_controller_is_refused_and_cancel_becomes_a_persisted_request(self):
        self.call('start')
        record = self.root / '.crewloom/active_workflow.json'
        self.assertTrue(record.is_file())
        self.assertEqual(json.loads(record.read_text())['workflow'], 'feature-batch')
        self.assertEqual(json.loads((self.root / '.crewloom/active_coordinator.json').read_text())
                         ['batch'], 'feature-batch')
        descriptor = os.open(str(self.root / '.crewloom/coordinators/feature-batch/controller.lock'),
                             os.O_RDWR)
        fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
        try:
            with self.assertRaisesRegex(ValueError, 'another live controller'):
                self.call('run')
            with self.assertRaisesRegex(ValueError, 'another live controller'):
                self.call('start')
            requested = self.call('cancel', reason='second controller test')
            self.assertEqual(requested['status'], 'cancellation_requested')
            self.assertFalse(requested['drained'])
        finally:
            os.close(descriptor)
        marker = self.root / '.crewloom/coordinators/feature-batch/cancel.request'
        self.assertTrue(marker.is_file())
        self.assertEqual(json.loads(marker.read_text())['reason'], 'second controller test')
        self.assertEqual((marker.stat().st_mode & 0o777), 0o600)
        self.call('run')
        self.assertFalse(marker.exists(), 'a resumed run clears the cancellation request')

    def test_a_normal_workflow_cannot_take_the_reserved_root(self):
        self.call('start')
        plan = {'schema_version': 1, 'id': 'feature-batch', 'criteria': 'criteria.md',
                'steps': [{'id': 'build', 'role': ROLE, 'summary': 'Attempt an overlapping run',
                           'argv': ['python3', 'builder.py', 'other.txt'],
                           'inputs': ['input.txt'], 'outputs': ['other.txt']}]}
        (self.root / 'overlap.json').write_text(json.dumps(plan))
        read, fingerprint = w.read_plan(self.root, 'overlap.json')
        self.assertRaisesRegex(ValueError, 'unfinished workflow', w.reserve_workflow, self.root,
                               read, fingerprint)

    def test_a_native_context_task_cannot_take_the_reserved_root(self):
        self.call('start')
        binding = pb.load_binding(self.root)
        self.assertRaisesRegex(ValueError, 'unfinished managed workflow', pb.reserve, self.root,
                               binding, 'native-task', 'project-context')

    def test_a_second_batch_id_needs_a_new_committed_base(self):
        self.call('start')
        self.plan['id'] = 'other-batch'
        self.write_plan()
        with self.assertRaisesRegex(ValueError, 'uncommitted tracked changes'):
            self.call('start')

    def test_worktrees_bind_one_portable_project_and_distinct_git_identities(self):
        before = (self.root / '.crewloom/binding.json').read_text()
        self.call('start')
        self.assertEqual((self.root / '.crewloom/binding.json').read_text(), before,
                         'taking a batch never rewrites the root checkout binding')
        directories = set()
        for ident in ('left', 'right', 'combine'):
            path = self.worktree(ident)
            self.assertTrue((path / '.git').is_file())
            self.assertFalse((path / '.crewloom/binding.json').exists(),
                             'a worktree gets its own local checkout binding when it first runs')
            self.assertEqual(self.git_in(path, 'symbolic-ref', '--short', 'HEAD'),
                             'crewloom/feature-batch/' + ident)
            self.assertEqual(self.git_in(path, 'rev-parse', 'HEAD'), self.base)
            identity = self.git_in(path, 'rev-parse', '--absolute-git-dir')
            self.assertNotIn(identity, directories, 'each worktree has its own Git directory')
            directories.add(identity)
            self.assertEqual(Path(self.git_in(path, 'rev-parse', '--git-common-dir')).name, '.git')
        self.assertEqual(self.git('rev-parse', 'HEAD'), self.base)

    def git_in(self, path, *arguments):
        result = subprocess.run(['git', *arguments], cwd=str(path),
                                env=repo_map.git_environment(), capture_output=True, text=True,
                                check=False, timeout=30)
        if result.returncode:
            raise AssertionError('git ' + ' '.join(arguments) + ' failed in ' + str(path)
                                 + ': ' + result.stderr.strip())
        return result.stdout.strip()

    def test_worktree_identity_drift_is_refused_without_destructive_repair(self):
        self.call('start')
        path = self.worktree('left')
        self.git_in(path, 'checkout', '-q', '-b', 'someone-elses-branch')
        with self.assertRaisesRegex(ValueError, 'is on branch'):
            self.call('run')
        self.assertTrue((path / '.git').is_file(), 'the worktree is retained for inspection')
        self.assertEqual(self.git('rev-parse', 'HEAD'), self.base)

    def test_a_worktree_replaced_by_a_plain_directory_is_refused(self):
        self.call('start')
        path = self.worktree('left')
        path.rename(path.with_name('left-away'))
        path.mkdir()
        with self.assertRaisesRegex(ValueError, 'not a Git worktree'):
            self.call('run')

    def test_an_existing_branch_is_never_force_reused(self):
        self.git('branch', 'crewloom/feature-batch/left', self.base)
        with self.assertRaisesRegex(ValueError, 'already exists'):
            self.call('start')
        self.assertFalse((self.root / '.crewloom/active_workflow.json').exists())

    def test_a_foreign_coordinator_reservation_blocks_the_root(self):
        self.call('start')
        (self.root / '.crewloom/active_coordinator.json').write_text(json.dumps(
            {'schema_version': 1, 'project_root': str(self.root),
             'project_id': 'coordinator-fixture', 'checkout_id': 'a' * 32,
             'batch': 'other-batch', 'manifest': 'other.json', 'manifest_sha256': 'b' * 64,
             'reserved_at': '2026-10-04T00:00:00+00:00'}))
        with self.assertRaisesRegex(ValueError, 'coordinator batch other-batch'):
            self.call('validate')
        with self.assertRaisesRegex(ValueError, 'coordinator batch other-batch'):
            self.call('run')

    def test_a_foreign_workflow_or_native_task_reservation_blocks_the_root(self):
        self.call('start')
        (self.root / '.crewloom/active_coordinator.json').unlink()
        (self.root / '.crewloom/active_workflow.json').write_text(json.dumps(
            {'project_root': str(self.root), 'workflow': 'other-workflow',
             'plan_sha256': 'c' * 64}))
        with self.assertRaisesRegex(ValueError, 'managed workflow other-workflow'):
            self.call('validate')
        (self.root / '.crewloom/active_workflow.json').unlink()
        (self.root / '.crewloom/active_task.json').write_text(json.dumps(
            {'schema_version': 1, 'project_root': str(self.root),
             'project_id': 'coordinator-fixture', 'checkout_id': 'a' * 32,
             'task_id': 'native-task', 'owner': 'project-context',
             'reserved_at': '2026-10-04T00:00:00+00:00'}))
        with self.assertRaisesRegex(ValueError, 'native context task native-task'):
            self.call('validate')


class ManifestRevalidationBoundaries(CoordinatorFixture):
    def test_a_changed_manifest_is_refused_for_every_stateful_action(self):
        self.call('start')
        self.plan['workers'] = 1
        self.write_plan()
        self.git('add', 'coordinator.json')
        self.git('commit', '-qm', 'Narrow the workers')
        for action in ('run', 'start', 'status', 'cancel'):
            with self.subTest(action=action):
                self.assertRaisesRegex(ValueError, 'manifest_sha256|workers_changed|frozen',
                                       self.call, action)


class ModelWorkflowFixture(CoordinatorFixture):
    """A batch whose tasks are real model steps verified by real container commands.

    Two independent tasks each generate one Python module through the managed `model` step, then
    run an acceptance command inside Docker that imports the generated file and checks its numeric
    behaviour. The integration workflow declares all four task outputs as inputs, so its combined
    acceptance can only pass by reading code the model step produced.
    """

    @classmethod
    def _build(cls, root):
        cls._git(root, 'init', '-q')
        cls._git(root, 'config', 'gc.auto', '0')
        cls._git(root, 'config', 'maintenance.auto', 'false')
        cls._git(root, 'config', 'user.name', 'Coordinator fixture')
        cls._git(root, 'config', 'user.email', 'fixture@example.invalid')
        config = pb.default_config('coordinator-fixture', 'observe')
        (root / pb.CONFIG_NAME).write_text(json.dumps(config))
        pb.bootstrap(root, project_id='coordinator-fixture')
        # The managed model step builds its prompt from the project-local role, so the role is
        # installed in the project and frozen in the base commit the worktrees start from.
        installed, errors = crewloom.install_skills(root, 'agents', [ROLE], False)
        if errors:
            raise AssertionError('role install failed: ' + ', '.join(errors))
        (root / 'input.txt').write_text('frozen fixture input\n')
        (root / 'criteria.md').write_text(
            '- Every generated module is imported and behaves as the acceptance requires.\n')
        (root / 'verify_feature.py').write_text(ACCEPT_FEATURE)
        (root / 'verify_combined.py').write_text(ACCEPT_COMBINED)
        (root / 'workflows').mkdir()
        (root / 'feature_left.md').write_text(
            'Implement a left pricing helper that doubles one integer value.\n')
        (root / 'feature_right.md').write_text(
            'Implement a right tax helper that triples one integer value.\n')
        for label in ('left', 'right'):
            plan = {'schema_version': 1, 'id': label + '-workflow', 'criteria': 'criteria.md',
                    'steps': [
                        {'id': 'generate', 'role': ROLE, 'kind': 'model',
                         'summary': 'Implement the ' + label + ' feature',
                         'host': 'openai', 'model': 'fixture-model',
                         'inputs': ['feature_' + label + '.md'],
                         'outputs': ['src/' + label + '_feature.py']},
                        {'id': 'accept', 'role': ROLE,
                         'summary': 'Run the generated ' + label + ' feature in the container',
                         'argv': ['python3', 'verify_feature.py', 'src/' + label + '_feature.py',
                                  label, 'artifacts/' + label + '_result.json'],
                         'inputs': ['src/' + label + '_feature.py', 'verify_feature.py'],
                         'outputs': ['artifacts/' + label + '_result.json']}]}
            (root / 'workflows' / (label + '.json')).write_text(json.dumps(plan))
        integration = {'schema_version': 1, 'id': 'integration-workflow', 'criteria': 'criteria.md',
                       'steps': [{'id': 'accept-combined', 'role': 'qa-test-automation-engineer',
                                  'summary': 'Accept the combined generated result',
                                  'argv': ['python3', 'verify_combined.py'],
                                  'inputs': ['input.txt', 'verify_combined.py',
                                             'src/left_feature.py', 'src/right_feature.py',
                                             'artifacts/left_result.json',
                                             'artifacts/right_result.json'],
                                  'outputs': ['artifacts/acceptance.json']}]}
        (root / 'workflows' / 'integration.json').write_text(json.dumps(integration))
        plan = {'schema_version': 1, 'id': 'feature-batch', 'project_id': 'coordinator-fixture',
                'base': 'HEAD', 'workers': 2,
                'tasks': [{'id': 'left', 'workflow': 'workflows/left.json', 'depends_on': []},
                          {'id': 'right', 'workflow': 'workflows/right.json', 'depends_on': []}],
                'integration': {'workflow': 'workflows/integration.json'}}
        (root / 'coordinator.json').write_text(json.dumps(plan))
        cls._git(root, 'add', '.')
        cls._git(root, 'commit', '-qm', 'Freeze the model coordinator fixture')

    def declare_native_cli(self, ident, host='opencode'):
        """Point one task's model step at an installed CLI host and commit the opt-in."""
        plan = json.loads((self.root / 'workflows' / (ident + '.json')).read_text())
        plan['steps'][0]['host'] = host
        plan['steps'][0].pop('model', None)
        (self.root / 'workflows' / (ident + '.json')).write_text(json.dumps(plan))
        for task in self.plan['tasks']:
            if task['id'] == ident:
                task['native_host_cli'] = True
        self.write_plan()
        self.git('add', 'workflows/' + ident + '.json', 'coordinator.json')
        self.git('commit', '-qm', 'Declare the native CLI host for ' + ident)
        return self.git('rev-parse', 'HEAD')

    def commit_base(self):
        self.git('add', '.')
        self.git('commit', '--allow-empty', '-qm', 'Freeze the model coordinator base')
        self.base = self.git('rev-parse', 'HEAD')
        return self.base


class ModelWorkflowBoundaries(ModelWorkflowFixture):
    """Model steps are accepted only where a real command acceptance can consume what they generate."""

    def test_a_model_only_workflow_is_refused_without_writes(self):
        plan = json.loads((self.root / 'workflows/left.json').read_text())
        plan['steps'] = [plan['steps'][0]]
        plan['id'] = 'left-model-only'
        (self.root / 'workflows/left.json').write_text(json.dumps(plan))
        self.commit_base()
        before = self.snapshot()
        result = self.cli('validate')
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('needs a real command acceptance', result.stdout)
        self.assertEqual(self.snapshot(), before, 'a refused model plan wrote project state')

    def test_a_generated_artifact_no_command_accepts_is_refused_without_writes(self):
        plan = json.loads((self.root / 'workflows/right.json').read_text())
        plan['steps'][1]['inputs'] = ['verify_feature.py']
        plan['steps'][1]['argv'] = ['python3', 'verify_feature.py', 'verify_feature.py', 'right',
                                     'artifacts/right_result.json']
        (self.root / 'workflows/right.json').write_text(json.dumps(plan))
        self.commit_base()
        before = self.snapshot()
        result = self.cli('validate')
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('must be read by a later real command acceptance', result.stdout)
        self.assertEqual(self.snapshot(), before, 'an unconsumed artifact was accepted preflight')

    def test_one_consumed_artifact_does_not_excuse_another_generated_one(self):
        plan = json.loads((self.root / 'workflows/left.json').read_text())
        plan['steps'][0]['outputs'] = ['src/left_feature.py', 'docs/left_notes.md']
        (self.root / 'workflows/left.json').write_text(json.dumps(plan))
        self.commit_base()
        result = self.cli('validate')
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('generates what nothing consumes: docs/left_notes.md', result.stdout)

    def test_an_earlier_command_cannot_stand_in_for_a_later_acceptance(self):
        plan = json.loads((self.root / 'workflows/left.json').read_text())
        plan['steps'].reverse()
        (self.root / 'workflows/left.json').write_text(json.dumps(plan))
        self.commit_base()
        self.assertNotEqual(self.cli('validate').returncode, 0)

    def test_a_native_cli_host_is_refused_before_the_provider_without_the_opt_in(self):
        plan = json.loads((self.root / 'workflows/left.json').read_text())
        plan['steps'][0]['host'] = 'opencode'
        plan['steps'][0].pop('model', None)
        (self.root / 'workflows/left.json').write_text(json.dumps(plan))
        self.commit_base()
        requests = []
        with mock.patch.object(model_host, 'generate', _stand_in_provider(requests)):
            result = self.cli('run', 'coordinator-fixture', '--allow-host-cli')
        self.assertNotEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn('needs an explicit operator opt-in', result.stdout + result.stderr)
        self.assertEqual(requests, [], 'no provider was reached before the refusal')
        self.assertEqual(self.git('rev-parse', 'HEAD'), self.base)
        self.assertFalse(self.worktree('left').exists(), 'no worktree was created for a refused plan')

    def test_a_manifest_opt_in_alone_does_not_reach_the_provider(self):
        base = self.declare_native_cli('left')
        requests = []
        with mock.patch.object(model_host, 'generate', _stand_in_provider(requests)):
            report = self.call('run')
        states = {item['id']: item for item in report['tasks']}
        self.assertNotEqual(states['left']['status'], 'verified')
        self.assertIn('operator opt-in', states['left']['error'])
        self.assertNotIn('opencode', [item['host'] for item in requests],
                         'the manifest declaration alone reached no installed CLI host')
        self.assertFalse((self.worktree('left') / 'src/left_feature.py').exists())
        self.assertIsNone(states['left']['commit'])
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)

    def test_the_explicit_operator_flag_is_carried_to_the_generation_and_no_further(self):
        self.declare_native_cli('left')
        requests = []
        with mock.patch.object(model_host, 'generate', _stand_in_provider(requests)):
            report = self.call('run', allow_host_cli=True)
        states = {item['id']: item for item in report['tasks']}
        self.assertEqual({item['id'] for item in report['tasks'] if item['native_host_cli']},
                         {'left'}, 'only the declared task may use an installed CLI host')
        self.assertEqual(states['left']['native_host_cli'], True)
        self.assertEqual(states['right']['native_host_cli'], False)
        self.assertEqual([item['host'] for item in requests if item['host'] in model_host.CLI_HOSTS],
                         ['opencode'], 'the installed CLI host was reached only for the opted-in task')
        self.assertEqual({item['outputs'][0] for item in requests if item['host'] in model_host.CLI_HOSTS},
                         {'src/left_feature.py'})
        if states['left']['status'] == 'verified':
            self.assertEqual(states['left']['declared_outputs'],
                             ['src/left_feature.py', 'artifacts/left_result.json'])

    def test_a_non_boolean_native_cli_opt_in_is_refused(self):
        self.plan['tasks'][0]['native_host_cli'] = 'yes'
        self.write_plan()
        self.commit_base()
        self.assertNotEqual(self.cli('validate').returncode, 0)
        self.plan['integration']['native_host_cli'] = 1
        self.plan['tasks'][0].pop('native_host_cli')
        self.write_plan()
        self.commit_base()
        self.assertNotEqual(self.cli('validate').returncode, 0)

    def test_a_manual_task_step_is_still_refused_in_a_model_workflow(self):
        plan = json.loads((self.root / 'workflows/right.json').read_text())
        plan['steps'].insert(1, {'id': 'review', 'role': ROLE, 'kind': 'task',
                                 'summary': 'Wait for a human decision this batch cannot grant',
                                 'inputs': ['feature_right.md'], 'outputs': ['notes.md']})
        (self.root / 'workflows/right.json').write_text(json.dumps(plan))
        self.commit_base()
        result = self.cli('validate')
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('execute no manual task step', result.stdout)


@unittest.skipUnless(os.environ.get('CREWLOOM_DOCKER_TESTS') == '1',
                     'Enable real Docker coordinator acceptance explicitly')
class DockerCoordinatorTests(CoordinatorFixture):
    """One real batch: two overlapping tasks, a dependency that sees its ancestors, and publication."""

    def setUp(self):
        super().setUp()
        self.image = w.inspect_image(w.DEFAULT_IMAGE)

    def test_two_workers_overlap_and_a_child_sees_its_ancestors(self):
        report = self.call('run')
        self.assertEqual(report['status'], 'verified', report)
        self.assertTrue(report['workers_overlapped'], 'recorded task intervals did not overlap')
        checkout = {item['id']: item['checkout_id'] for item in report['tasks']}
        self.assertEqual(len(set(checkout.values())), 3, 'each worktree needs its own checkout ID')
        for item in report['tasks']:
            self.assertEqual(item['status'], 'verified')
            self.assertNotEqual(item['commit'], self.base)
            self.assertTrue(item['ledger'], 'recorded executor evidence is required')
        combine = next(item for item in report['tasks'] if item['id'] == 'combine')
        self.assertEqual(sorted(combine['dependencies']), ['left', 'right'])
        self.assertIn('combine.txt', (self.worktree('combine') / 'combine.txt').read_text())
        self.assertNotIn('right.txt', (self.worktree('left') / 'left.txt').read_text())
        self.assertEqual((self.root / 'left.txt').read_text(), 'base content\n',
                         'the root keeps its base bytes until reviewed publication')
        for name in ('right.txt', 'combine.txt', 'artifacts/acceptance.json'):
            self.assertFalse((self.root / name).exists(),
                             'no descendant artifact may appear in the root before publication')

    def test_a_failed_task_blocks_its_dependent_and_publication(self):
        broken = self.root / 'workflows/right.json'
        plan = json.loads(broken.read_text())
        plan['steps'][0]['argv'] = ['python3', 'absent-script.py', 'right.txt']
        plan['steps'][0]['summary'] = 'Deliberately unusable command'
        broken.write_text(json.dumps(plan))
        self.git('add', 'workflows/right.json')
        self.git('commit', '-qm', 'Break one independent task')
        base = self.git('rev-parse', 'HEAD')
        report = self.call('run')
        self.assertNotEqual(report['status'], 'verified')
        states = {item['id']: item for item in report['tasks']}
        self.assertNotEqual(states['right']['status'], 'verified')
        # The refused task names the acceptance that actually failed, by its own step and owning
        # role, instead of reporting a finished run that recorded no cause.
        self.assertIn('finished as failed', states['right']['error'])
        self.assertIn('step build (role ' + ROLE + ') failed: Command failed: build',
                      states['right']['error'])
        self.assertNotIn('no error recorded', states['right']['error'])
        self.assertIsNone(states['right']['commit'])
        recorded = json.loads((self.worktree('right') / '.crewloom/workflows/right-workflow'
                               / 'state.json').read_text())['error']
        run_state = json.loads((self.worktree('right') / '.crewloom/workflows/right-workflow'
                               / 'state.json').read_text())
        self.assertEqual(run_state['plan_file'], 'workflows/right.json')
        self.assertEqual(recorded, 'Command failed: build',
                         'the managed run must carry the failing stage\'s own cause')
        self.assertEqual(states['combine']['status'], 'blocked')
        self.assertIn('Blocked by right', states['combine']['error'])
        self.assertFalse((self.root / '.crewloom/active_coordinator.json').exists())
        with self.assertRaisesRegex(ValueError, 'unverified tasks'):
            self.call('prepare')
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)


    def test_full_publication_path_and_a_replayed_decision(self):
        self.assertEqual(self.call('run')['status'], 'verified')
        prepared = self.call('prepare')
        self.assertEqual(prepared['status'], 'review_ready')
        integration = prepared['integration']
        self.assertEqual(integration['base'], self.base)
        self.assertNotEqual(integration['head'], self.base)
        self.assertTrue(integration['merged'])
        self.assertTrue(integration['ledger'], 'the combined acceptance needs recorded executor evidence')
        self.assertEqual(integration['reviewed_artifacts'], 4)
        acceptance = json.loads((self.worktree('integration') / 'artifacts/acceptance.json')
                                .read_text())
        self.assertTrue(acceptance['combined_acceptance'])
        self.assertEqual(sorted(acceptance['artifacts']), ['combine.txt', 'left.txt', 'right.txt'])
        self.assertTrue(all(item['marker_found'] for item in acceptance['artifacts'].values()))
        with self.assertRaisesRegex(ValueError, 'explicit reviewed decision'):
            self.call('publish', expected_base=integration['base'],
                      candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        review = self.call('review', principal='reviewer-alex',
                           expected_base=integration['base'], candidate_head=integration['head'],
                           diff_sha256=integration['diff_sha256'])
        self.assertEqual(review['principal'], 'reviewer-alex')
        self.assertEqual(review['method'], 'declared-label')
        with self.assertRaisesRegex(ValueError, 'not the candidate base'):
            self.call('review', principal='reviewer-alex', expected_base='0' * 64,
                      candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        with self.assertRaisesRegex(ValueError, 'not the prepared candidate'):
            self.call('review', principal='reviewer-alex', expected_base=integration['base'],
                      candidate_head='0' * 64, diff_sha256=integration['diff_sha256'])
        self.assertEqual(self.call('run')['status'], 'verified')
        with self.assertRaisesRegex(ValueError, 'explicit reviewed decision'):
            self.call('publish', expected_base=integration['base'],
                      candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        integration = self.call('prepare')['integration']
        self.call('review', principal='reviewer-alex', expected_base=integration['base'],
                  candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        published = self.call('publish', expected_base=integration['base'],
                              candidate_head=integration['head'],
                              diff_sha256=integration['diff_sha256'])
        self.assertEqual(published['status'], 'published')
        self.assertEqual(self.git('rev-parse', 'HEAD'), integration['head'])
        for name in ('left.txt', 'right.txt', 'combine.txt', 'artifacts/acceptance.json'):
            self.assertTrue((self.root / name).is_file(), name)
        self.assertTrue(self.worktree('left').is_dir(), 'evidence-bound worktrees are retained')
        self.assertFalse((self.root / '.crewloom/active_coordinator.json').exists())
        self.assertRaisesRegex(ValueError, 'already consumed|explicit reviewed decision|frozen base_commit',
                               self.call, 'publish', expected_base=integration['base'],
                               candidate_head=integration['head'],
                               diff_sha256=integration['diff_sha256'])
        consumed = json.loads((self.root / '.crewloom/coordinators/feature-batch'
                               '/review-nonces.json').read_text())['consumed']
        self.assertEqual(len(consumed), 1)
        self.assertEqual(consumed[0]['head'], integration['head'])
        with self.assertRaisesRegex(ValueError, 'already consumed'):
            tc._consume_nonce(self.root / '.crewloom/coordinators/feature-batch',
                              published['review']['proof'], 'feature-batch', integration['head'])
        self.assertRaisesRegex(ValueError, 'cannot run again|frozen base_commit', self.call, 'run')

    def test_a_failing_combined_acceptance_blocks_publication(self):
        broken = self.root / 'verify_combined.py'
        broken.write_text(ACCEPTANCE.replace("'marked left'", "'marked nothing'"))
        self.git('add', 'verify_combined.py')
        self.git('commit', '-qm', 'Demand a marker no task produces')
        base = self.git('rev-parse', 'HEAD')
        self.assertEqual(self.call('run')['status'], 'verified')
        with self.assertRaisesRegex(ValueError, 'Combined acceptance failed'):
            self.call('prepare')
        status = self.call('status')
        self.assertEqual(status['status'], 'failed')
        self.assertIsNone(status['integration'])
        self.assertIsNone(status['review'])
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)
        with self.assertRaisesRegex(ValueError, 'prepare the combined candidate'):
            self.call('review', principal='reviewer-alex', expected_base=base,
                      candidate_head='0' * 40, diff_sha256='0' * 64)
        with self.assertRaisesRegex(ValueError, 'explicit reviewed decision'):
            self.call('publish', expected_base=base, candidate_head='0' * 40, diff_sha256='0' * 64)
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)

    def test_verified_resume_adds_no_new_executor_attempts(self):
        self.assertEqual(self.call('run')['status'], 'verified')
        before = {}
        for ident in ('left', 'right', 'combine'):
            ledger = json.loads((self.worktree(ident) / '.crewloom/attempts.json').read_text())
            before[ident] = len(ledger['attempts'])
        self.assertTrue(all(count >= 1 for count in before.values()))
        resumed = self.call('run')
        self.assertEqual(resumed['status'], 'verified')
        self.assertTrue(resumed['resumed'])
        for item in resumed['tasks']:
            self.assertEqual(item['attempts'], 1)
            ledger = json.loads((self.worktree(item['id']) / '.crewloom/attempts.json').read_text())
            self.assertEqual(len(ledger['attempts']), before[item['id']],
                             'a verified task must not be executed again on resume')

    def test_cancel_preserves_the_root_and_the_verified_work(self):
        report = self.call('run', workers=1)
        self.assertEqual(report['status'], 'verified')
        published = self.call('prepare')['integration']
        self.call('review', principal='reviewer-alex', expected_base=published['base'],
                  candidate_head=published['head'], diff_sha256=published['diff_sha256'])
        cancelled = self.call('cancel', reason='operator changed the plan')
        self.assertEqual(cancelled['status'], 'cancelled')
        self.assertEqual(sorted(cancelled['verified']), ['combine', 'left', 'right'])
        self.assertEqual(self.git('rev-parse', 'HEAD'), self.base)
        self.assertEqual(self.call('status')['status'], 'cancelled')
        self.assertRaisesRegex(ValueError, 'reviewed|cancelled', self.call, 'publish',
                               expected_base=published['base'],
                               candidate_head=published['head'],
                               diff_sha256=published['diff_sha256'])
        resumed = self.call('run')
        self.assertEqual(resumed['status'], 'verified')
        for item in resumed['tasks']:
            self.assertEqual(item['attempts'], 1)

    def _declare_a_contested_path(self):
        """Two independent tasks declare the same output path with different content."""
        for ident in ('left', 'right'):
            source = self.root / ('workflows/' + ident + '.json')
            plan = json.loads(source.read_text())
            plan['steps'][0]['argv'] = ['python3', 'builder.py', ident + '.txt', ident]
            plan['steps'].append({'id': 'shared', 'role': ROLE,
                                  'summary': 'Write a differently marked shared artifact',
                                  'argv': ['python3', 'builder.py', 'shared.txt', ident],
                                  'inputs': ['input.txt', 'builder.py'], 'outputs': ['shared.txt']})
            source.write_text(json.dumps(plan))
        integration = json.loads((self.root / 'workflows/integration.json').read_text())
        integration['steps'][0]['inputs'].append('shared.txt')
        (self.root / 'workflows/integration.json').write_text(json.dumps(integration))
        self.git('add', 'workflows/left.json', 'workflows/right.json',
                 'workflows/integration.json')
        self.git('commit', '-qm', 'Let two independent tasks own one contested path')
        return self.git('rev-parse', 'HEAD')

    def test_a_descendant_is_refused_when_its_ancestors_conflict(self):
        base = self._declare_a_contested_path()
        report = self.call('run', workers=1)
        states = {item['id']: item['status'] for item in report['tasks']}
        self.assertEqual(states['left'], 'verified')
        self.assertEqual(states['right'], 'verified')
        self.assertEqual(states['combine'], 'blocked')
        self.assertIn('conflict', next(item for item in report['tasks']
                                       if item['id'] == 'combine')['error'])
        self.assertNotEqual((self.worktree('left') / 'shared.txt').read_text(),
                            (self.worktree('right') / 'shared.txt').read_text())
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)
        for ident in ('left', 'right', 'combine'):
            self.assertTrue((self.worktree(ident) / '.git').is_file())

    def test_final_integration_conflicts_keep_every_branch_and_worktree(self):
        self.plan['tasks'][2]['depends_on'] = ['left']
        self.write_plan()
        self._declare_a_contested_path()
        self.git('add', 'coordinator.json')
        self.git('commit', '-qm', 'Combine depends on one independent task only')
        base = self.git('rev-parse', 'HEAD')
        self.assertEqual(self.call('run', workers=1)['status'], 'verified')
        with self.assertRaisesRegex(ValueError, 'conflict'):
            self.call('prepare')
        status = self.call('status')
        self.assertEqual(status['status'], 'conflict')
        self.assertIn('shared.txt', status['integration']['conflicts'])
        self.assertIsNone(status['review'])
        for ident in ('left', 'right', 'combine'):
            self.assertTrue((self.worktree(ident) / '.git').is_file())
            self.assertEqual(self.git('rev-parse', 'refs/heads/crewloom/feature-batch/' + ident),
                             self.git_in(self.worktree(ident), 'rev-parse', 'HEAD'))
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)
        with self.assertRaisesRegex(ValueError, 'prepare the combined candidate'):
            self.call('review', principal='reviewer-alex', expected_base=base,
                      candidate_head='0' * 40, diff_sha256='0' * 64)

    def git_in(self, path, *arguments):
        result = subprocess.run(['git', *arguments], cwd=str(path),
                                env=repo_map.git_environment(), capture_output=True, text=True,
                                check=False, timeout=30)
        if result.returncode:
            raise AssertionError('git ' + ' '.join(arguments) + ' failed in ' + str(path)
                                 + ': ' + result.stderr.strip())
        return result.stdout.strip()

    def test_untracked_root_collisions_block_publication_and_other_files_survive(self):
        self.assertEqual(self.call('run')['status'], 'verified')
        integration = self.call('prepare')['integration']
        self.call('review', principal='reviewer-alex', expected_base=integration['base'],
                  candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        (self.root / 'right.txt').write_text('untracked local file at a candidate path\n')
        (self.root / 'notes.md').write_text('unrelated untracked work\n')
        before = self.git('rev-parse', 'HEAD')
        with self.assertRaisesRegex(ValueError, 'collide'):
            self.call('publish', expected_base=integration['base'],
                      candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        self.assertEqual(self.git('rev-parse', 'HEAD'), before)
        self.assertEqual((self.root / 'notes.md').read_text(), 'unrelated untracked work\n')
        self.assertEqual((self.root / 'right.txt').read_text(),
                         'untracked local file at a candidate path\n')
        (self.root / 'right.txt').unlink()
        self.assertEqual(self.call('publish', expected_base=integration['base'],
                                   candidate_head=integration['head'],
                                   diff_sha256=integration['diff_sha256'])['status'], 'published')

    def test_a_revoked_credential_stops_publication(self):
        import reviewer_credentials as rc
        config = pb.load_config(self.root)[0]
        config['policy']['review'] = {'mode': 'verified', 'allow_self_review': False}
        (self.root / pb.CONFIG_NAME).write_text(json.dumps(config))
        pb.bootstrap(self.root, project_id='coordinator-fixture')
        self.git('add', pb.CONFIG_NAME)
        self.git('commit', '-qm', 'Require a verified reviewer')
        base = self.git('rev-parse', 'HEAD')
        principal, token = rc.register(self.root, 'reviewer-alex')
        self.assertEqual(principal, 'reviewer-alex')
        self.assertEqual(self.call('run')['status'], 'verified')
        prepared = self.call('prepare')['integration']
        proof = self.call('review', principal=None, expected_base=prepared['base'],
                          candidate_head=prepared['head'], diff_sha256=prepared['diff_sha256'],
                          token=token)
        self.assertEqual(proof['method'], 'hashed-token')
        rc.revoke(self.root, 'reviewer-alex')
        with self.assertRaisesRegex(ValueError, 'revoked'):
            self.call('publish', expected_base=prepared['base'],
                      candidate_head=prepared['head'], diff_sha256=prepared['diff_sha256'])
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)
        self.assertNotEqual(prepared['head'], base)

    def test_a_missing_credential_is_refused_in_verified_mode(self):
        import reviewer_credentials as rc
        config = pb.load_config(self.root)[0]
        config['policy']['review'] = {'mode': 'verified', 'allow_self_review': False}
        (self.root / pb.CONFIG_NAME).write_text(json.dumps(config))
        pb.bootstrap(self.root, project_id='coordinator-fixture')
        self.git('add', pb.CONFIG_NAME)
        self.git('commit', '-qm', 'Require a verified reviewer')
        rc.register(self.root, 'reviewer-alex')
        self.assertEqual(self.call('run')['status'], 'verified')
        prepared = self.call('prepare')['integration']
        with self.assertRaises(ValueError):
            self.call('review', principal=None, expected_base=prepared['base'],
                      candidate_head=prepared['head'], diff_sha256=prepared['diff_sha256'])
        with self.assertRaisesRegex(ValueError, 'identifier|credential|token'):
            self.call('review', principal='reviewer-alex', expected_base=prepared['base'],
                      candidate_head=prepared['head'], diff_sha256=prepared['diff_sha256'])

    def test_stale_evidence_after_a_rewrite_is_refused_before_publication(self):
        self.assertEqual(self.call('run')['status'], 'verified')
        integration = self.call('prepare')['integration']
        self.call('review', principal='reviewer-alex', expected_base=integration['base'],
                  candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        (self.worktree('left') / 'left.txt').write_text('edited after verification\n')
        with self.assertRaisesRegex(ValueError, 'no longer holds|changed since verification'):
            self.call('publish', expected_base=integration['base'],
                      candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        self.assertEqual(self.git('rev-parse', 'HEAD'), self.base)

    def test_hooks_still_run_and_a_hook_failure_leaves_recoverable_state(self):
        base = self.git('rev-parse', 'HEAD')
        self.assertEqual(self.call('start')['status'], 'planned')
        common = Path(self.git_in(self.worktree('left'), 'rev-parse', '--path-format=absolute',
                                  '--git-common-dir'))
        hook = common / 'hooks/pre-commit'
        hook.parent.mkdir(parents=True, exist_ok=True)
        hook.write_text('#!/bin/sh\nexit 1\n')
        hook.chmod(0o755)
        report = self.call('run')
        self.assertNotEqual(report['status'], 'verified')
        left = next(item for item in report['tasks'] if item['id'] == 'left')
        self.assertNotEqual(left['status'], 'verified')
        self.assertTrue((self.worktree('left') / 'left.txt').is_file(),
                        'a refused commit keeps the produced artifact for inspection')
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)
        hook.unlink()
        self.assertEqual(self.call('run')['status'], 'verified')


@unittest.skipUnless(os.environ.get('CREWLOOM_DOCKER_TESTS') == '1',
                     'Enable real Docker model-task acceptance explicitly')
class DockerModelWorkflowTests(ModelWorkflowFixture):
    """Real model tasks: generation in isolated worktrees, acceptance by real container commands.

    The provider is a stand-in, so these cases say nothing about any model's quality. What they
    prove is the part this toolkit owns: two model steps run concurrently in separate worktrees,
    the container imports what was generated and checks its behaviour, the combined acceptance
    reads the committed generated bytes, and the root moves only after a reviewed decision.
    """

    def setUp(self):
        super().setUp()
        self.image = w.inspect_image(w.DEFAULT_IMAGE)

    def test_two_model_tasks_verify_in_isolated_worktrees_and_publish_after_review(self):
        requests = []
        with mock.patch.object(model_host, 'generate', _stand_in_provider(requests)):
            report = self.call('run')
        self.assertEqual(report['status'], 'verified', report)
        self.assertTrue(report['workers_overlapped'], 'the two model tasks did not overlap')
        self.assertEqual(sorted(item['host'] for item in requests), ['openai', 'openai'],
                         'only the two declared model steps may reach a provider')
        self.assertEqual(sorted(item['task'] for item in requests),
                         ['Implement the left feature', 'Implement the right feature'])
        checkout = {item['id']: item['checkout_id'] for item in report['tasks']}
        self.assertEqual(len(set(checkout.values())), 2, 'each worktree needs its own checkout ID')
        modules = {}
        for ident, function in (('left', 'double'), ('right', 'triple')):
            item = next(task for task in report['tasks'] if task['id'] == ident)
            self.assertEqual(item['status'], 'verified')
            self.assertEqual(item['model_steps'], ['generate'])
            self.assertFalse(item['native_host_cli'])
            generated = [entry for entry in item['ledger'] if entry.get('kind') == 'model']
            self.assertEqual(len(generated), 1, 'the generation attempt needs recorded evidence')
            self.assertEqual(generated[0]['host'], 'openai')
            self.assertEqual([entry['step'] for entry in generated[0]['consumed_by']], ['accept'])
            self.assertEqual(generated[0]['consumed_by'][0]['sha256'],
                             generated[0]['outputs']['src/' + ident + '_feature.py'])
            command = [entry for entry in item['ledger'] if entry.get('kind') is None]
            self.assertEqual([entry['step'] for entry in command], ['accept'])
            self.assertTrue(command[0]['image_id'], 'the acceptance needs the real image it ran in')
            modules[ident] = (self.worktree(ident) / ('src/' + ident + '_feature.py')).read_text()
            self.assertEqual(modules[ident], GENERATED[function])
            self.assertEqual((self.worktree(ident) / ('artifacts/' + ident + '_result.json'))
                             .exists(), True)
        self.assertNotEqual(modules['left'], modules['right'])
        self.assertFalse((self.worktree('left') / 'src/right_feature.py').exists(),
                         'an independent model task must not see another task generated module')
        self.assertEqual(self.git('rev-parse', 'HEAD'), self.base,
                         'the root must not move before a reviewed publication')
        for name in ('src', 'artifacts'):
            self.assertFalse((self.root / name).exists(),
                             'no generated artifact may appear in the root before publication')
        prepared = self.call('prepare')
        self.assertEqual(prepared['status'], 'review_ready')
        integration = prepared['integration']
        self.assertEqual(integration['reviewed_artifacts'], 5)
        acceptance = json.loads((self.worktree('integration') / 'artifacts/acceptance.json')
                                .read_text())
        self.assertTrue(acceptance['combined_acceptance'])
        self.assertEqual(sorted(acceptance['observed']), ['left', 'right'])
        self.assertEqual(acceptance['observed']['left']['value'], 42)
        self.assertEqual(acceptance['observed']['right']['value'], 42)
        with self.assertRaisesRegex(ValueError, 'explicit reviewed decision'):
            self.call('publish', expected_base=integration['base'],
                      candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        self.assertEqual(self.git('rev-parse', 'HEAD'), self.base)
        self.call('review', principal='reviewer-alex', expected_base=integration['base'],
                  candidate_head=integration['head'], diff_sha256=integration['diff_sha256'])
        published = self.call('publish', expected_base=integration['base'],
                              candidate_head=integration['head'],
                              diff_sha256=integration['diff_sha256'])
        self.assertEqual(published['status'], 'published')
        self.assertEqual(self.git('rev-parse', 'HEAD'), integration['head'])
        self.assertEqual((self.root / 'src/left_feature.py').read_text(), modules['left'])
        self.assertTrue(json.loads((self.root / 'artifacts/acceptance.json').read_text())
                        ['combined_acceptance'])

    def test_a_combined_acceptance_failure_blocks_review_and_keeps_the_root(self):
        # The acceptance is weakened before the batch starts: the base commit is frozen at run
        # time, and moving it afterwards is refused for a different, equally honest reason.
        broken = (self.root / 'verify_combined.py').read_text().replace(
            'module.triple(14)', 'module.triple(14) + 1')
        (self.root / 'verify_combined.py').write_text(broken)
        self.git('add', 'verify_combined.py')
        self.git('commit', '-qm', 'Demand tax behaviour the generated code does not have')
        base = self.git('rev-parse', 'HEAD')
        requests = []
        with mock.patch.object(model_host, 'generate', _stand_in_provider(requests)):
            self.assertEqual(self.call('run')['status'], 'verified')
            with self.assertRaisesRegex(ValueError, 'Combined acceptance failed'):
                self.call('prepare')
        status = self.call('status')
        self.assertEqual(status['status'], 'failed')
        self.assertIsNone(status['integration'])
        self.assertIsNone(status['review'])
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)
        with self.assertRaisesRegex(ValueError, 'prepare the combined candidate'):
            self.call('review', principal='reviewer-alex', expected_base=base,
                      candidate_head='0' * 40, diff_sha256='0' * 64)
        with self.assertRaisesRegex(ValueError, 'explicit reviewed decision'):
            self.call('publish', expected_base=base, candidate_head='0' * 40, diff_sha256='0' * 64)
        self.assertFalse((self.root / 'artifacts').exists())

    def test_a_native_cli_model_task_verifies_end_to_end_with_the_operator_flag(self):
        base = self.declare_native_cli('left', host='opencode')
        requests = []
        # The committed manifest decision alone reaches no installed CLI host, and it survives
        # that refusal: the recorded task still carries the intent its own commit declared.
        with mock.patch.object(model_host, 'generate', _stand_in_provider(requests)):
            refused = self.call('run')
        left = next(item for item in refused['tasks'] if item['id'] == 'left')
        self.assertEqual(left['status'], 'blocked')
        self.assertIn('operator opt-in', left['error'])
        self.assertEqual(left['ledger'], [])
        self.assertIs(left['native_host_cli'], True)
        self.assertEqual(left['native_cli_run'],
                         {'declared': True, 'operator_flag': False, 'granted': False,
                          'hosts': ['opencode'], 'at': left['native_cli_run']['at']})
        self.assertEqual(self.git('rev-parse', 'HEAD'), base)
        self.assertFalse((self.worktree('left') / 'src/left_feature.py').exists())
        # The same batch retried with the second decision: same root, same batch id, same intent.
        with mock.patch.object(model_host, 'generate', _stand_in_provider(requests)):
            report = self.call('run', allow_host_cli=True)
            self.assertEqual(report['status'], 'verified', report)
            prepared = self.call('prepare')
        self.assertTrue(report['resumed'])
        self.assertEqual(prepared['status'], 'review_ready')
        hosts = sorted(item['host'] for item in requests)
        self.assertEqual(hosts, ['openai', 'opencode'])
        left = next(item for item in report['tasks'] if item['id'] == 'left')
        self.assertTrue(left['native_host_cli'])
        self.assertTrue(left['native_cli_run']['granted'])
        self.assertEqual([entry['host'] for entry in left['ledger'] if entry.get('kind') == 'model'],
                         ['opencode'])
        self.assertEqual((self.worktree('left') / 'src/left_feature.py').read_text(),
                         GENERATED['double'])
        self.assertEqual(json.loads((self.worktree('integration') / 'artifacts/acceptance.json')
                                    .read_text())['combined_acceptance'], True)

    def test_a_verified_model_task_is_not_generated_again_on_resume(self):
        requests = []
        with mock.patch.object(model_host, 'generate', _stand_in_provider(requests)):
            self.assertEqual(self.call('run')['status'], 'verified')
            resumed = self.call('run')
        self.assertEqual(resumed['status'], 'verified')
        self.assertEqual(len(requests), 2, 'each verified model task keeps exactly one attempt')
        for item in resumed['tasks']:
            self.assertEqual(item['attempts'], 1)
            ledger = json.loads((self.worktree(item['id']) / '.crewloom/attempts.json').read_text())
            self.assertEqual(len([entry for entry in ledger['attempts']
                                  if entry.get('kind') == 'model']), 1)


if __name__ == '__main__':
    unittest.main()
